import { CommonModule, DatePipe } from '@angular/common';
import { Component, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../core/api.service';import { WorkspaceStore } from '../core/workspace.store';import type { BillingState, Invitation, OnboardingState, WorkspaceAdminSettings } from '../models';
@Component({standalone:true,imports:[CommonModule,FormsModule,DatePipe],template:`
<div class="page-head"><div><p class="eyebrow">PHASE 11 · SAAS FOUNDATION</p><h1>Workspace settings</h1><p class="muted">Onboarding, invitations, configuration and billing-ready workspace state.</p></div></div>
@if(onboarding();as o){<article class="card settings-card"><div class="panel-head"><div><p class="eyebrow">ONBOARDING</p><h2>{{o.percent}}% complete</h2></div><span>{{o.completed}} / {{o.total}}</span></div><progress [max]="o.total" [value]="o.completed"></progress><div class="onboarding-steps">@for(s of o.steps;track s.key){<span [class.done]="s.complete">{{s.complete?'✓':'○'}} {{s.label}}</span>}</div></article>}
<section class="notification-grid"><article class="card settings-card"><p class="eyebrow">WORKSPACE</p><h2>General</h2><label>Name<input [(ngModel)]="name"></label><label>Description<textarea [(ngModel)]="description"></textarea></label><label>Timezone<input [(ngModel)]="timezone"></label><label>Week starts<select [(ngModel)]="weekStartsOn"><option value="monday">Monday</option><option value="sunday">Sunday</option></select></label><button class="btn primary" (click)="save()">Save settings</button></article>
<article class="card settings-card"><p class="eyebrow">INVITATIONS</p><h2>Invite teammates</h2><label>Email<input [(ngModel)]="inviteEmail" type="email"></label><label>Role<select [(ngModel)]="inviteRole"><option>member</option><option>viewer</option><option>manager</option><option>admin</option></select></label><button class="btn primary" (click)="invite()">Create invitation</button>@for(i of invitations();track i.id){<div class="automation-row"><span class="automation-kind">{{i.role}}</span><div><strong>{{i.email}}</strong><small>{{i.status}} · {{i.created_at|date:'short'}}</small></div></div>}</article></section>
@if(billing();as b){<article class="card settings-card"><div class="panel-head"><div><p class="eyebrow">BILLING-READY</p><h2>{{b.plan|titlecase}} plan</h2></div><span class="pill">{{b.status}}</span></div><p>{{b.seats_used}} / {{b.seats}} seats used</p><p class="muted">Checkout is intentionally disabled; the domain model is ready for a future billing provider integration.</p></article>}`})
export class SettingsComponent{private readonly api=inject(ApiService);readonly store=inject(WorkspaceStore);readonly onboarding=signal<OnboardingState|null>(null);readonly invitations=signal<Invitation[]>([]);readonly billing=signal<BillingState|null>(null);name='';description='';timezone='Africa/Johannesburg';weekStartsOn:'monday'|'sunday'='monday';inviteEmail='';inviteRole='member';constructor(){effect(()=>{const w=this.store.current();if(w)this.load(w.id);});}save(){const w=this.store.current();if(!w)return;this.api.updateWorkspaceSettings(w.id,{name:this.name,description:this.description,timezone:this.timezone,weekStartsOn:this.weekStartsOn}).subscribe(()=>this.load(w.id));}invite(){const w=this.store.current();if(!w||!this.inviteEmail)return;this.api.invite(w.id,this.inviteEmail,this.inviteRole).subscribe(()=>{this.inviteEmail='';this.load(w.id);});}private load(id:string){this.api.workspaceSettings(id).subscribe((v:WorkspaceAdminSettings)=>{this.name=v.workspace.name;this.description=v.workspace.description;this.timezone=v.settings.timezone;this.weekStartsOn=v.settings.week_starts_on;});this.api.onboarding(id).subscribe(v=>this.onboarding.set(v));this.api.invitations(id).subscribe({next:v=>this.invitations.set(v),error:()=>this.invitations.set([])});this.api.billing(id).subscribe(v=>this.billing.set(v));}}